//renders our homepage

import Feed from '@components/Feed';
//rafce is the shortcut
//don't need to import react
//can run this page by going to localhost:3000/home - npm run dev

const Home = () => {
  return (
    // this gives us the center column with flex-col
    <section className="w-full flex-center flex-col">
        <h1 className="head_text text-center">
            The Power of AI
            <br className="max-md:hidden"/>
            <span className="orange_gradient text-center"> AI-Powered Prompts</span>
        </h1>

        <p className="desc text-center">
            Prompt-astic is an open-source tool that is generated by AI robots that will take over our modern world if we are not careful. We can share prompts, be excited and wait for the AI to control our human world.
        </p>
        <Feed />
    </section>
  )
}

export default Home